/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:d534727d-b964-4661-a22d-4f8c9fd0437c",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_BTeY0TRU3",
    "aws_user_pools_web_client_id": "6193ilk393ljc90o1k6ij7phpn",
    "oauth": {}
};


export default awsmobile;
